title = "PHYsec Key Generation configuration file"

[metadata]
title = "FLoRa but using single bit lossless quant instead of mbr_lossless"

[keygen]
is_master = true
keygen_id = 23
csi_type = 0
pre_process_type = 0
quant_type = 24
recon_type = 1
probe_padding = 10
probe_delay = 250 

[telemetry]
enabled = true
logging_enabled = true
keygen_info_enabled = true

[radio]
modulation = "LoRa"

[radio.radio_config] 
spreading_factor = 7
bandwidth = 250
tx_power = 5


