title = "PHYsec Key Generation configuration file"

[metadata]
title = "Dummy Expe1"
title_alias = "Expe1"

[keygen]
is_master = false
keygen_id = 23
csi_type = 0
pre_process_type = 0
quant_type = 2
recon_type = 2
probe_padding = 10
probe_delay = 250

[telemetry]
enabled = true
logging_enabled = true
keygen_info_enabled = true

[radio]
modulation = "LoRa"

[radio.radio_config] 
spreading_factor = 7 
bandwidth = 125
tx_power = 8


