#pragma once

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#include "types.h"

/*!
 * Quantization Parameters
 */
#define QP_DIFFERENTIAL_RESOLUTION 2
#define QP_SB_RESOLUTION 1

// the LSB of quant_type tells
// if the quantization is lossy or not
// The second LSB of quant_type tells
// if the quantization is blockwise or not
#define QUANT_LOSSY_MASK (1)
#define QUANT_BLOCKWISE_MASK (2) // 1<<1
#define QUANT_IS_LOSSY(quant_type) (quant_type & (QUANT_LOSSY_MASK))
#define QUANT_IS_BLOCKWISE(quant_type) (quant_type & (QUANT_BLOCKWISE_MASK))
#define QUANT_IS_EXCURSION(quant_type)                                         \
  (((quant_type) == QUANT_SB_EXCURSION_LOSSY ||                                \
    (quant_type) == QUANT_MB_EXCURSION_LOSSY))

/*!
 * Quantization types.
 *
 * The LSB of the enum represent if the quantization
 * is lossy with a need post-process or not. So all the even numbers are
 * lossless when the odd numbers are the lossy quantization types
 */
// typedef enum __attribute__((__packed__)) {
//	// multi-bit level-crossing scaled on range (han2023flora)
//	QUANT_MBR_LOSSLESS = 0,
//	// multi-bit level-crossing with guard bands scaled on entropy
//(xu2019lorakey, junejo2022loralisk, gao2021novel) 	QUANT_MBE_LOSSY = 2,
//	// single-bit differential with guard band (zhang2018channel)
//	QUANT_SB_DIFF_LOSSY = 1,
//	// single-bit excursion lossy (han2019distributed)
//	QUANT_SB_EXCURSION_LOSSY = 3,
//	// multi-bit excursion lossy (han2020lorabased)
//	QUANT_MB_EXCURSION_LOSSY = 5,
//	// quantization with variable level-crossing regarding randomness of set
//(chen2023adaptive) 	QUANT_ADAPTIVE = 7, } quant_type_t;

typedef enum __attribute__((__packed__)) {
  QUANT_MBR_LOSSLESS = (0),                                            // 2
  QUANT_MBE_LOSSY = (1) << 2 | QUANT_BLOCKWISE_MASK,                   // 6
  QUANT_SB_DIFF_LOSSY = (2) << 2 | QUANT_LOSSY_MASK,                   // 9
  QUANT_SB_EXCURSION_LOSSY = (3) << 2 | QUANT_LOSSY_MASK,              // 13
  QUANT_MB_EXCURSION_LOSSY = (4) << 2 | QUANT_LOSSY_MASK,              // 17
  QUANT_ADAPTIVE = (5) << 2 | QUANT_LOSSY_MASK | QUANT_BLOCKWISE_MASK, // 23
  QUANT_SB_LOSSLESS = (6) << 2,                                        // 24
  QUANT_SB_LOSSLESS_BLOCKWISE = (6) << 2 | QUANT_BLOCKWISE_MASK,       // 26
  QUANT_SB_LOSSY = (7) << 2 | QUANT_LOSSY_MASK,                        // 29
  QUANT_SB_LOSSY_BLOCKWISE =
      (7) << 2 | QUANT_LOSSY_MASK | QUANT_BLOCKWISE_MASK, // 31
} quant_type_t;

// typedef enum __attribute__((__packed__)) {
//     QUANT_MULTIBIT_RANGE = (0) << 2 | QUANT_BLOCKWISE_MASK,
//     QUANT_MULTIBIT_ENTROPY = (1) << 2 | QUANT_BLOCKWISE_MASK,
//     QUANT_SINGLEBIT_DIFF = (2) << 2 | QUANT_LOSSY_MASK,
//     QUANT_SINGLEBIT_EXCURSION = (3) << 2 | QUANT_BLOCKWISE_MASK |
//     QUANT_LOSSY_MASK, QUANT_MULTIBIT_EXCURSION = (4) << 2 |
//     QUANT_BLOCKWISE_MASK | QUANT_LOSSY_MASK, QUANT_ADAPTIVE = (5) << 2 |
//     QUANT_LOSSY_MASK | QUANT_BLOCKWISE_MASK,
// } quant_type_t;

/*!
 *	Dynamic Quantization Diversity Block information
 */
typedef struct {
  // ID for diversity block start (first index in measurement set)
  uint32_t start;
  // ID for diversity block end (last index in measurement set)
  uint32_t end;
  // number of bits quantized per sample in the diversity block
  uint8_t nbits_per_sample;
} dynquant_diversity_block_t;

/*!
 *	Quantization parameters
 */
// Allow knowing how many bits where generated by sample, boundaries of the
// sequences when the number of bits to quantize is dynamically decided
typedef struct __attribute__((__packed__)) {
  bool dynamic;
  union {
    uint8_t nbits_per_sample;
    dynquant_diversity_block_t *diversity_blocks_info;
  };
} quant_lossy_params_t;

typedef struct __attribute__((__packed__)) {
  uint8_t value;
  quant_index_t index;
} quant_excursion_index_t;

/*!
 *	\brief	Generate graycode of an integer value (8 bits)
 *
 *	\param[in]	n	the integer value to convert to graycode
 *
 *	\returns	the graycode of the integer value
 */
uint8_t graycode_u8(uint8_t n);

/*!
 *  \brief  Add bits to a bitstring key at a specific location. Used to
 * concatenate keys.
 *
 *  \param[in, out]  key         the bitstring key
 *  \param[in]       key_size    the size of the key in bits (to not exceed when
 * copying bits)
 *  \param[in]       at          the location to add the bits
 *  \param[in]       bitstring   the bitstring to add
 *  \param[in]       n_bits      the number of bits to add
 *
 *  \returns    the new size in bits
 *
 */
int add_bits_to_key(uint8_t *key, size_t key_size_in_bits, size_t at,
                    uint8_t *bitstring, size_t n_bits);

uint8_t get_bit_at(const uint8_t *key, size_t key_size_in_bits, size_t at);

/*!
 *	\brief Determine if there is enough CSI to quantized
 *
 *	\param[in]	qtype	quantization method used
 *	\param[in]	num_csi	the number of gathered CSI
 */
// bool quant_is_enough_csi(quant_type_t qtype, size_t num_csi);

/*!
 *	\brief	Drop bits corresponding to some CSI indexes
 *
 *	\param[in, out]	key				the bit key (should be
 *allocated to a size of at least `⌊key_size_in_bits/8⌋ + 8`
 *	\param[in]	key_size_in_bits	the number of bits in the key
 *	\param[in]	already_dropped		array containing the indexes of
 *already dropped samples
 *	\param[in]	num_already_dropped	number of already dropped
 *samples
 *	\param[in]	to_drop				new lossy points to
 *dropp in the `key`
 *	\param[in]	num_to_drop			number of samples to
 *drop
 *
 *	\returns	the number of bits kept in key
 */
uint32_t quant_dropp_csis(quant_lossy_params_t *qparams, uint8_t *key,
                          size_t key_size_in_bits, uint32_t *indexes,
                          size_t num_indexes);

/*!
 *  \brief Remove all bits not part of the indexes array (inverse of
 * quant_dropp_csis: Selecting bits instead of dropping)
 *
 *  \param[in, out]  key             the bit key (should be allocated to a
 *  \param[in]       key_size_in_bits    the number of bits in the key
 *  \param[in]       indexes         array containing the indexes of samples to
 * keep
 *  \param[in]       num_indexes     number of samples to keep
 *
 *  \returns    the number of bits kept in key
 */
uint32_t quant_retain_csis(quant_lossy_params_t *qparams, uint8_t *key,
                           size_t key_size_in_bits, uint32_t *indexes,
                           size_t num_indexes);

uint32_t quant_merge_csi_indexes(quant_index_t *indexes,
                                 size_t *actual_num_indexes,
                                 size_t indexes_capacity,
                                 quant_index_t *new_indexes,
                                 size_t num_new_indexes);

/*!
 * \brief	Construct an array of indexes from excursions (discard the
 *excursion value)
 *
 * \param[in]		excursions		array of excursions
 * \param[in]		num_excursions	number of excursions in the array
 * \param[out]		indexes			array to fill with the indexes
 * \param[in, out]	num_indexes		the maximum number of indexes
 *possible to fill, modified with the actual number of indexes
 *
 *	\returns	true if the indexes are successfully extracted, false
 *otherwise (if *num_indexes is too small)
 */
// bool quant_sb_excursion_get_indexes(quant_excursion_index_t
// *excursions, size_t num_excursions, quant_index_t *indexes, size_t
// *num_indexes);
//
// bool quant_sb_excursion_reconstruct_excursions(quant_index_t *indexes,
// size_t num_indexes, quant_excursion_index_t *excursions, size_t
// *num_excursions);

/*!
 * \brief	Merge bit excursions. Check for excursion in both arguments sets
 *			that are the same (equivalent to (existing_excursions ∩
 *other_excursions))
 *
 *	\param[in, out]	existing_excursions		array of excursions to
 *merge
 *	\param[in, out]	num_max_excursions		number of excursions in
 *the `existing_excursions` array
 *	\param[in]		other_excursions		array of
 *excursions to merge
 *	\param[in]		num_other_excursions	number of excursions in
 *the `other_excursions` array
 *
 *	 \returns	the number of excursions in the merged array
 *(representing the number of bits the excursion based quantization should
 *generate)
 */
// uint32_t quant_merge_excursions(quant_excursion_index_t
// *existing_excursions, size_t *num_max_excursions, uint32_t *other_excursions,
// size_t num_other_excursions);

int quant_sb_lossless(csi_t *measures, size_t n_measures, uint8_t *outkey,
                      size_t key_size);

int quant_sb_lossy(csi_t *measures, size_t n_measures, uint8_t *outkey,
                   size_t key_size, quant_index_t *indexes,
                   size_t *num_indexes);

/*!
 *	\brief	Multi-bit quantization with guard band (number of level based on
 *	measurement set entropy)
 *
 *	\param	measures		CSI measurements array
 *	\param	n_measures		Number of measures
 *	\param	alpha			The guard band to data ratio
 *	\param	outkey			The outputed key buffer
 *	\param	key_size		The size of the key in bytes
 *	\param	lossy_points	An array to fill with dropped measurements (can
 *be NULL, LoRa-Key doesn't share lossy points)
 *	\param	num_lossy		Number of lossy points filled. Must be
 *set to the `lossy_points` initial size (should be >= n_measures) (can be NULL,
 *ignored if `lossy_points` is NULL)
 *
 *	\returns	number of generated bits if quantization succeed, -1
 *otherwise
 */
int quant_mbe_lossy(int16_t *measures, size_t n_measures, float alpha,
                    uint8_t *outkey, size_t key_size, uint32_t *lossy_points,
                    size_t *num_lossy);

/*!
 *	\brief	Multi-bit quantization without guard band (number of level based
 *on measurement set max-min range)
 *
 *	\param	measures		CSI measurements array
 *	\param	n_measures		Number of measures
 *	\param	outkey			The outputed key buffer
 *	\param	key_size		The size of the key in bytes
 */
bool measurements_sufficiency_check_mbr_lossless(int16_t *measures,
                                                 size_t nb_measures);
int quant_mbr_lossless(int16_t *measures, size_t n_measures, uint8_t *outkey,
                       size_t key_size);

/*!
 *   \brief single-bit differential quantization
 *
 *	\param	measures		CSI measurements array
 *	\param	n_measures		Number of measures
 *	\param	outkey			The outputed key buffer
 *	\param	key_size		The size of the key in bytes
 *	\param	lossy_points	An array to fill with dropped measurements
 *	\param	num_lossy		Number of lossy points filled. Must be
 *set to the `lossy_points` initial size (should be >= n_measures)
 */
int quant_sb_diff_lossy(int16_t *measures, size_t n_measures, uint8_t *outkey,
                        size_t key_size, uint32_t *lossy_points,
                        size_t *num_lossy);

int quant_adaptive(int16_t *measures, size_t n_measures, uint8_t *outkey,
                   size_t key_size, uint32_t *lossy_points, size_t *num_lossy);

/*!
 *	\brief	Retrieves single-bit quantization excursions from a set of
 *measures (Alice function)
 *
 *	\param[in]	measures		the CSI measurements array
 *	\param[in]	n_measures		the number of measures
 *	\param[out]	excursions		the array to fill with the
 *excursions
 *	\param[out]	num_excursions	the maximum number of excursions
 *possible in the array (modified with the actual number of generated
 *excursions)
 *	\param[in]	m				size of an excursion
 *(number of contiguous quantized bits that need to be the same)
 *	\param[in]	alpha			 custom parameter for crafting
 *the guard band
 *	\param[in]	key_size		the size of the key in bytes
 *(helping to determine the number of excursion required)
 */
// int quant_sb_excursion_get_excursions(int16_t *measures, size_t
// n_measures, quant_excursion_index_t *excursions, size_t *num_excursions,
// uint8_t m, float alpha, size_t key_size);

/*!
 *	\brief	Quantize measures at indexes specified by Alice and reconstruct
 *			an excursion set that Bob and Alice can generate bits
 *for. (Bob function)
 *
 *	\param[in]		measures			the CSI
 *measurements array
 *	\param[in]		n_measures			the number of
 *measures
 *	\param[in, out]	excursions_indexes	the excursions center indexes
 *sent by Alice, modified with the indexes selected by Bob
 * \param[out]		excursions			the array to fill with
 *the excursions (should be allocated to a size of at least `num_excursions`,
 *										the
 *initial size of `excursions_indexes`)
 * \param[in, out]	num_excursions		the number of excursions in
 *`excursions_indexes`, modified with the actual number of selected excursions
 *
 *	\param[in]		m					size of
 *an excursion (number of contiguous quantized bits that need to be the same)
 *	\param[in]		alpha				custom parameter
 *for crafting the guard band
 *	\param[in]		key_size			the size of the
 *key in bytes (helping to determine the number of excursion required)
 *
 *	\returns	Number of selected excursions if there is enough to
 *generate a key, -1 otherwise
 */
// int quant_sb_excursion_get_valid_excursions_from_indexes(int16_t
// *measures, size_t n_measures, quant_index_t *excursions_indexes, size_t
// num_indexes, quant_excursion_index_t *excursions, size_t *num_excursions,
// uint8_t m, float alpha, size_t key_size);

/*!
 *	\brief	Quantize the excursions of a set of measures to a bitstring key
 *
 *	\param[in]	excursions		the array of excursions to
 *quantize
 *	\param[in]	num_excursions	the number of excursions in the array
 *	\param[out]	outkey			the outputed key buffer
 *	\param[in]	key_size		the size of the key in bytes
 *
 *	\returns	Number of generated bits if quantization succeed, -1
 *otherwise
 */
// int quant_sb_excursion_quantize(quant_excursion_index_t *excursions,
// size_t num_excursions, uint8_t *outkey, size_t key_size);

void quant_excursion_select_random_subset(quant_index_t *indexes,
                                          size_t *num_indexes);

/*!
 * \brief  Intersect two sets of indexes
 *
 * \param[in, out]  indexes    the first set of indexes
 * \param[in, out]  num_indexes    the number of indexes in the first set
 * (updated with new number of indexes)
 * \param[in]       new_indexes the second set of indexes
 * \param[in]       num_new_indexes the number of indexes in the second set
 *
 * \returns    the number of indexes in the intersection
 */
uint32_t quant_inter_csi_indexes(quant_index_t *indexes,
                                 size_t *actual_num_indexes,
                                 size_t indexes_capacity,
                                 quant_index_t *new_indexes,
                                 size_t num_new_indexes);

int quant_sb_excursion_quantize2(csi_t *measures, size_t n_measures,
                                 quant_index_t *indexes, size_t *num_indexes,
                                 uint8_t m, float alpha, uint8_t *outkey,
                                 size_t key_size);

int quant_mb_excursion_quantize2(quant_lossy_params_t *qparams, csi_t *measures,
                                 size_t n_measures, quant_index_t *indexes,
                                 size_t *num_indexes, uint8_t m,
                                 uint8_t *outkey, size_t key_size);
