#pragma once

#include <stdint.h>
#include <stdlib.h>

#include "libphysec/libphysec.h"
#include "physec_config.h"

#define UART_PHYSEC_TELEMETRY_MAGIC 0x7e1e3e71

// Telemetry packet types
enum __attribute__((__packed__)) {
  PHYSEC_TELEMETRY_LOGGING = 0,
  PHYSEC_TELEMETRY_KG_CONF,
  PHYSEC_TELEMETRY_KG_INFO,
  PHYSEC_TELEMETRY_CSIS,
  PHYSEC_TELEMETRY_NUM_CMD
};

#define KEY_SIZE 16

typedef struct __attribute__((__packed__)) {
  uint32_t magic;
  uint8_t type;
  uint8_t data[];
} physec_telemetry_packet_t;

typedef struct __attribute__((__packed__)) {
  uint16_t size;
  // null terminated CString
  uint8_t msg[];
} physec_telemetry_logging_t;

typedef physec_load_csi physec_telemetry_csi_t;

typedef physec_keygen_config physec_telemetry_keygen_config_t;

enum __attribute__((__packed__)) {
  STAGE_PROBING = 0,
  STAGE_PRE_PROCESS,
  STAGE_QUANTIZATION,
  STAGE_POST_PROCESS,
  STAGE_RECONCILIATION,
  STAGE_PRIVACY_AMPLIFICATION,
  STAGE_NUM
};

enum __attribute__((__packed__)) {
  // Key generated by the quantization stage (without post process)
  KEY_TYPE_QUANT = 0,
  // Key after post processing
  KEY_TYPE_POST_PROCESSING,
  // Key after reconciliation
  KEY_TYPE_RECONCILIATION,
  // Key after privacy amplification
  KEY_TYPE_PRIVACY_AMPLIFICATION,
  // Public / Private key combo
  KEY_TYPE_ECDH_PUBLIC_PRIVATE_KEYS,
  // Peer public key after they sent it to us
  KEY_TYPE_ECDH_PEER_PUBLIC_KEY,
  // Derived shared secret
  KEY_TYPE_ECDH_SHARED_SECRET,
  // Final AES key
  KEY_TYPE_NUM
};

typedef struct __attribute__((__packed__)) {
  uint8_t key_type;
  uint16_t num_bits;
  uint8_t key[]; // holds ((num_bits + 8 - 1) / 8) bytes (rounded up)
} physec_telemetry_keygen_info_t;

extern physec_config physec_conf;

size_t physec_telemetry_get_size(physec_telemetry_packet_t *packet);
int physec_telemetry_log(bool ts, const char *fmt, ...);
void physec_telemetry_send_csis(csi_t *csis, size_t num_csis);
void physec_telemetry_send_keygen_conf(physec_config *info);
void physec_telemetry_send_keygen_info(uint8_t key_type, const uint8_t *key,
                                       size_t num_bits);
